name: test trigger
on: 
  release:
    types: [published]
jobs:
  get_release_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Get Release Tag
        id: get_release_tag
        run: echo "The release tag is ${{ github.event.release.tag_name }}"
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
      - name: echo env
        run : echo "${{ env.RELEASE_TAG }}"